version: "3"
services:
 web:
  image: apotheoun/cardsapi:1.0
  deploy: 
   replicas: 3
   resources:
    limits:
     cpus: "0.1"
     memory: 50M
   restart_policy:
    condition: on-failure
  ports:
   - "8080:8080"
  networks:
   - webnet
networks:
  webnet: 
